### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by zhugelianglongming** [bfenetworks/ingress-bfe#53]
# 背景
[BFE](https://github.com/bfenetworks/bfe) 支持对流量进行[重定向](https://www.bfe-networks.net/en_us/modules/mod_redirect/mod_redirect/)，希望 bfe-ingress-controller 实现该功能。

# 配置方式
Ingress 资源内
* spec.rules 定义路由规则
* metadata.annotations 定义对符合路由规则的流量，重定向响应的行为

参考格式：
``` Yaml
metadata:
    annotations:
        bfe.ingress.kubernetes.io/redirect.target: "https://www.baidu.com"
        bfe.ingress.kubernetes.io/redirect.status: 302
spec:
  rules:
  - ...
``` 
``` Yaml
metadata:
    annotations:
        bfe.ingress.kubernetes.io/redirect.cmd: SCHEME_SET
        bfe.ingress.kubernetes.io/redirect.params: '["http"]'
        bfe.ingress.kubernetes.io/redirect.status: 302
spec:
  rules:
  - ...
``` 

# 重定向类型
通过设置重定向返回状态码 bfe.ingress.kubernetes.io/redirect.status ，配置重定向类型
* 默认为 302 临时重定向
## 永久重定向
``` Yaml
bfe.ingress.kubernetes.io/redirect.status: 301
```
``` Yaml
bfe.ingress.kubernetes.io/redirect.status: 308
```
## 临时重定向
``` Yaml
bfe.ingress.kubernetes.io/redirect.status: 302
``` 

# 重定向目标
通过特定 annotation 配置重定向目标，可设置为以下模式其中之一：
* 静态 URL
* 动态 URL

## 静态 URL
通过设置 bfe.ingress.kubernetes.io/redirect.target ，配置静态重定向目标URL
``` Yaml
bfe.ingress.kubernetes.io/redirect.target: "https://www.baidu.com"
```
对应示例
* request:  http://host/path?query-key=value 
* response:  https://www.baidu.com 

## 动态 URL
通过设置 bfe.ingress.kubernetes.io/redirect.cmd 、 bfe.ingress.kubernetes.io/redirect.params ，配置静态重定向目标URL

### 设置 Scheme
``` Yaml
bfe.ingress.kubernetes.io/redirect.cmd: SCHEME_SET
bfe.ingress.kubernetes.io/redirect.params: '["http"]'
``` 
对应示例
* request:  https://host/path?query-key=value 
* response:  http://host/path?query-key=value 

### 从Query中获得URL
``` Yaml
bfe.ingress.kubernetes.io/redirect.cmd: URL_FROM_QUERY
bfe.ingress.kubernetes.io/redirect.params: '["url"]'
``` 
对应示例
* request:  https://host/path?url=https%3A%2F%2Fwww.baidu.com 
* response:  https://www.baidu.com

### 添加前缀
``` Yaml
bfe.ingress.kubernetes.io/redirect.cmd: URL_PREFIX_ADD
bfe.ingress.kubernetes.io/redirect.params: '["http://www.baidu.com/redirect"]'
``` 
对应示例
* request:  https://host/path?query-key=value 
* response:  http://www.baidu.com/redirect/path?query-key=value

> https://www.bfe-networks.net/en_us/modules/mod_redirect/mod_redirect/
