### ISSUE TITLE
支持 Openshift Route 模型

### ISSUE THREAD

**Issue by zhugelianglongming** [bfenetworks/ingress-bfe#76]
# 背景
K8s 环境中已通过 Openshift [Route][] 配置部分路由，希望 bfe-ingress-controller 兼容。
- Route [CRD][]

# 配置示例
``` yaml
apiVersion: route.openshift.io/v1
kind: Route
metadate:
  name: app
  namespace: default
spec:
  alternateBackends:
  - kind: Service
    name: app1
    weight: 20
  host: example.com
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: app
    weight: 80
  wildcardPolicy: None
```

[Route]: https://docs.okd.io/latest/rest_api/network_apis/route-route-openshift-io-v1.html
[CRD]: https://github.com/openshift/api/blob/master/route/v1/route.crd.yaml
